sudo: required
services:
  - docker

before_install:
  - docker build -t vnskln/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true vnskln/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-243838082233"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
